### ISSUE TITLE
'react_native_ticketmaster_ignite-Swift.h' file not found

### ISSUE THREAD

**Issue by ohsnapitscolin** [ticketmaster/react-native-ticketmaster-ignite#27]
Hey folks!

This repo is looking great so far! I'm working on migrating over from https://www.npmjs.com/package/@squidcloud/react-native-ticketmaster, and I'm running into the following issue when building for iOS:

```
› Compiling react-native-ticketmaster-ignite Pods/react-native-ticketmaster-ignite » RNTTicketsSdkEmbeddedViewManager.m

❌  (../node_modules/react-native-ticketmaster-ignite/ios/RNTTicketsSdkEmbeddedViewManager.m:3:9)

  1 | #import <React/RCTViewManager.h>
  2 | // Needed to use Swift files in Objective-C files
> 3 | #import <react_native_ticketmaster_ignite-Swift.h>
    |         ^ 'react_native_ticketmaster_ignite-Swift.h' file not found
  4 | 
  5 | @interface RNTTicketsSdkEmbeddedViewManager : RCTViewManager
  6 | @end
```

I believe I ran into this in the original repo, and addressed the issue with the code here: https://github.com/squidcloudio/react-native-ticketmaster/blob/main/ios/RNTTicketsSdkEmbeddedViewManager.m#L10-L15.

Making the same change to `RNTTicketsSdkEmbeddedViewManager.m` should resolve the issue.

**Comment by DanielOS7-TM** [comment]
Hey, glad our repo is looking good we will be updating this and bumping the SDK's used in this library shortly, will let you know when it's ready!

**Comment by joe-goodall-ticketmaster** [comment]
Hi @ohsnapitscolin the latest release of the library, v1.2.5, includes these changes 👍
