### ISSUE TITLE
Android SDK bump causes dependency conflict with expo updates

### ISSUE THREAD

**Issue by gbradybulls** [ticketmaster/react-native-ticketmaster-ignite#40]
The recent [Android SDK bump](https://github.com/ticketmaster/react-native-ticketmaster-ignite/pull/30/files) introduces a dependency on  `com.ticketmaster.accounts:authentication:3.8.0`, which has a transitive dependency `org.bouncycastle:bcpkix-jdk15on:1.70`, which in turn depends on `org.bouncycastle:bcprov-jdk15on:1.70` and `org.bouncycastle:bcutil-jdk15on:1.70`

Unfortunately, this breaks compatibility with expo/expo updates. The expo updates module has dependencies for `org.bouncycastle:bcprov-jdk15to18:1.70` and `org.bouncycastle:bcutil-jdk15to18:1.70` 

Trying to compile then results in numerous `Duplicate class` errors, as the jdk15on and jdk15to18 versions of these libraries can't coexist in the same project

I've tried excluding the jdk15on versions of these deps, but it results in an instant crash (which I assume indicicates there are at least some API differences between the older jdk15on versions and the newer jdk15to18 versions)

Currently, the only thing I can do to fix our build is use `dependencySubstitution` to specify `com.ticketmaster.accounts:authentication:3.6.0` and `com.ticketmaster.tickets:tickets:3.6.0` in our build, which obviously has big drawbacks. Those are the most recent versions that don't have the `org.bouncycastle:bcpkix-jdk15on:1.70` dependency, as far as I can tell.

Is there any chance `com.ticketmaster.accounts:authentication` might be updated to use the newer jdk15to18 version of `org.bouncycastle:bcpkix`?

Given the popularity of Expo / Expo Updates, I imagine this is an issue that will impact a lot of projects.

Thanks!

**Comment by joe-goodall-ticketmaster** [comment]
Hi @gbradybulls 
Thanks for bringing this up.
We're looking into this our side. Will give you an update asap.

**Comment by bryson-bulls** [comment]
@joe-goodall-ticketmaster any updates here?

**Comment by gbradybulls** [comment]
@joe-goodall-ticketmaster in the mean time, it would also be very helpful to know if running the SDK while pinning `com.ticketmaster.accounts:authentication` to `com.ticketmaster.tickets:tickets` to version `3.6.0` on Android (our current workaround) is a safe thing to be doing?

**Comment by joe-goodall-ticketmaster** [comment]
Hi @gbradybulls 

Sorry for not responding sooner. I've heard back from the team who has been working on this and they've just provided a fix which I've just smoke tested locally and all looks good. After further testing, if all looks good, we will update the library and release a new version of this library tomorrow. I'll update you here when done.

As a back up you should be fine to pin to version 3.6.0 but I think the better option would be the new version of the library.

**Comment by joe-goodall-ticketmaster** [comment]
Hi @gbradybulls 

We've just released a new version ([v1.5.1](https://github.com/ticketmaster/react-native-ticketmaster-ignite/releases/tag/v1.5.1)) with a fix for Expo incompatibility. Any issues please let us know.
