### ISSUE TITLE
Support for react native SDK 50+

### ISSUE THREAD

**Issue by mistycal98** [ticketmaster/react-native-ticketmaster-ignite#47]
Android Bundled 80ms node_modules/expo-router/entry.js (1 module)
 ERROR  TypeError: Cannot read property 'setConfig' of null
 
 IgniteProvider.tsx:70:19

**Comment by joe-goodall-ticketmaster** [comment]
Hi @mistycal98 

Can you give us a bit more context? I presume by 'Support for react native SDK 50+' you mean Expo 50+? Is your app a bare React Native app or Expo? Have you got an API key?

**Comment by joe-goodall-ticketmaster** [comment]
For privacy/confidentiality reasons all issues should now be directed to nexus_sdk@ticketmaster.com
