### ISSUE TITLE
Accounts SDK login error: No Auth Service Configurations defined

### ISSUE THREAD

**Issue by accesssolid** [ticketmaster/react-native-ticketmaster-ignite#49]
**Description**:
I’ve been trying to integrate the Ticketmaster SDK using the provided demo from the following repository: [https://github.com/ticketmaster/react-native-ticketmaster-ignite](https://github.com/ticketmaster/react-native-ticketmaster-ignite).

I passed the required `apiKey` and `clientName` into the `IgniteProvider` as shown below:

```jsx
<IgniteProvider
  // analytics={igniteAnalytics}
  options={{
    apiKey: '*************',
    clientName: '*****maker',
    primaryColor: '#000000',
  }}
>
```

However, I keep encountering the following error:  
**LOG: Accounts SDK login error: No Auth Service Configurations have been defined.**

I've also updated the demo constants as follows, but the error persists:

```js
export default {
  DEMO_VENUE_ID: 'KovZ917ANwG',
  DEMO_ATTRACTION_ID: 'K8vZ9171ov0',
  DEMO_EVENT_ID: 'G5dIZb8kECzK3',
};
```

**Expected Behavior**:  
The SDK should initialize properly and allow me to use the Ticket SDK modal as per my project requirements.

**Actual Behavior**:  
The error persists, indicating that no auth service configurations have been defined, despite passing the required parameters.

**Steps to Reproduce**:  
1. Clone the demo project from the [GitHub repo](https://github.com/ticketmaster/react-native-ticketmaster-ignite).
2. Pass the API key and client name as required.
3. Attempt to run the project and observe the error.

**Additional Context**:  
Any guidance on additional configurations or steps to resolve this would be greatly appreciated.

Thank you for your help!

**Comment by joe-goodall-ticketmaster** [comment]
For privacy/confidentiality reasons all issues should now be directed to nexus_sdk@ticketmaster.com
